### PR TITLE
Dev kmr

### PR DESCRIPTION
**Pull request by k-rister**

### CODE REVIEW

**Comment by k-rister** [comment]
@atheurer When I merge this it is likely to break people as they will most likely have to manually install the new version of trex (using --insecure).  Any thoughts on how we should communicate this?  Or just let it crash and burn?  I don't feel like we have a good handle on who all the let know other than our own immediate team.

**Comment by atheurer** [comment]
We could update the README finally

**Comment by atheurer** [comment]
Or we could catch the error message from curl and output something like "you may need to try --insecure".

**Comment by k-rister** [comment]
> We could update the README finally

This is definitely on my todo list.  I was thinking about it earlier but decided to get this done and merged first.

**Comment by k-rister** [comment]
> Or we could catch the error message from curl and output something like "you may need to try --insecure".

Yeah, I'll look into the error codes and output and see how easy it is to detect the exact problem.

**Pull request merged**
